/**
 * cosine_match.cpp
 * HLS Cosine Similarity Accelerator
 *
 * Build with Vivado HLS 2020.x:
 *   vivado_hls -f run_hls.tcl
 *
 * AXI-Lite register map (auto-generated by HLS, visible in .hwh):
 *   0x00        : ap_ctrl       (ap_start[0], ap_done[1], ap_idle[2], ap_ready[3])
 *   0x04        : ap_ctrl (GIE) (global interrupt enable)
 *   0x08        : ap_ctrl (IER) (interrupt enable register)
 *   0x0C        : ap_ctrl (ISR) (interrupt status register)
 *   0x10 - 0x13 : db_mem_lo     (lower 32 bits of db_mem AXI4 master address)
 *   0x14 - 0x17 : db_mem_hi     (upper 32 bits — unused on 32-bit Zynq)
 *   0x18 - 0x1B : num_users
 *   0x20 - 0x23 : best_idx      (output, read after done)
 *   0x28 - 0x2B : best_score    (output, raw Q4.28 fixed-point bits)
 *   0x100+      : query[0..127] (16-bit Q2.14 values, packed 2 per 32-bit word)
 *
 * Python access (PYNQ):
 *   accel = overlay.cosine_match_accel_0
 *   # write query, db pointer, num_users → start → poll done → read results
 *   (see fpga_interface.py for full driver)
 */

#include "cosine_match.h"
#include <string.h>

void cosine_match_accel(
    emb_t  query[EMB_DIM],
    emb_t  db_mem[MAX_USERS * EMB_DIM],
    int    num_users,
    int   *best_idx,
    acc_t *best_score
) {
    // -----------------------------------------------------------------
    // HLS Interface Pragmas
    // -----------------------------------------------------------------

    // AXI-Lite slave: control signals (ap_start / ap_done / ap_idle)
    #pragma HLS INTERFACE s_axilite port=return      bundle=CTRL

    // Query embedding passed in as AXI-Lite register bank starting at 0x100
    // 128 × 16-bit values → 64 × 32-bit register pairs
    #pragma HLS INTERFACE s_axilite port=query       bundle=CTRL offset=0x100
    #pragma HLS ARRAY_PARTITION variable=query       cyclic factor=8

    // Enrolled database read via AXI4 master (DMA from DDR where Python buffer lives)
    // The PS stores a PYNQ contiguous-memory buffer; its physical address is written
    // to the db_mem AXI-Lite register, and the HLS core DMA-reads on each invocation.
    #pragma HLS INTERFACE m_axi     port=db_mem      bundle=DB \
                                    depth=MAX_USERS*EMB_DIM    \
                                    max_read_burst_length=16   \
                                    num_read_outstanding=4
    #pragma HLS INTERFACE s_axilite port=db_mem      bundle=CTRL

    // Scalar inputs / outputs via AXI-Lite
    #pragma HLS INTERFACE s_axilite port=num_users   bundle=CTRL
    #pragma HLS INTERFACE s_axilite port=best_idx    bundle=CTRL
    #pragma HLS INTERFACE s_axilite port=best_score  bundle=CTRL

    // -----------------------------------------------------------------
    // Local DB buffer in BRAM (burst-loaded from DDR once per call)
    // -----------------------------------------------------------------
    emb_t local_db[MAX_USERS * EMB_DIM];
    #pragma HLS ARRAY_PARTITION variable=local_db cyclic factor=8
    // Partition factor=8 matches the MAC unroll below so each lane
    // gets its own BRAM port with no read-port conflicts.

    // Burst-read the enrolled database into on-chip BRAM.
    // With max_read_burst_length=16 and 32 users this is one AXI burst.
    int db_size = num_users * EMB_DIM;
    memcpy(local_db, db_mem, db_size * sizeof(emb_t));

    // -----------------------------------------------------------------
    // Dot-product search — compare query against every enrolled user
    // -----------------------------------------------------------------
    acc_t best  = acc_t(-2.0);   // worst possible dot product for unit vectors
    int   best_i = 0;

    user_loop:
    for (int u = 0; u < MAX_USERS; u++) {
        // HLS loop-tripcount hint for synthesis reports (does not affect logic)
        #pragma HLS LOOP_TRIPCOUNT min=1 max=MAX_USERS avg=8

        if (u >= num_users) break;   // only process enrolled users

        acc_t dot = acc_t(0.0);

        dot_loop:
        for (int d = 0; d < EMB_DIM; d++) {
            // PIPELINE II=1 means one MAC per cycle.
            // UNROLL factor=8 instantiates 8 parallel MAC lanes,
            // each backed by its own DSP48E1 block.
            // Effective throughput: 8 dimensions per cycle.
            // Latency per user: 128/8 = 16 cycles.
            #pragma HLS PIPELINE  II=1
            #pragma HLS UNROLL    factor=8
            dot += (acc_t)(query[d] * local_db[u * EMB_DIM + d]);
        }

        if (dot > best) {
            best   = dot;
            best_i = u;
        }
    }

    *best_idx   = best_i;
    *best_score = best;
}