"""
FPGA Interface Layer
Handles communication between PS (ARM CPU) and PL (FPGA logic).

PL Blocks:
  1. hdmi_stream_mux   : hardware HDMI kill switch (AXI GPIO auth_flag)
  2. cosine_match_accel: HLS dot-product accelerator for embedding search
  3. axi_vdma          : streams camera frames to HDMI OUT when unauthorized

cosine_match_accel AXI-Lite register map (generated by Vivado HLS):
  0x00        ap_ctrl     bit[0]=ap_start, bit[1]=ap_done, bit[2]=ap_idle
  0x10        db_mem_lo   physical address of enrolled-embeddings buffer (lo 32-bit)
  0x14        db_mem_hi   (upper 32-bit — always 0 on 32-bit Zynq)
  0x18        num_users   number of enrolled users in db_mem
  0x20        best_idx    output: index of closest enrolled user
  0x28        best_score  output: Q4.28 fixed-point dot product score
  0x100+      query[]     128 × int16 Q2.14 values packed as 64 × uint32

Fixed-point encoding (Q2.14):
  float → int16: round(f * 2**14)   clamped to [-32768, 32767]
  int16 → float: i / 2**14
"""

import numpy as np
import logging
import time
from typing import Optional, Tuple, List

try:
    from pynq import Overlay, allocate
    from pynq.lib.video import VideoIn, VideoOut, PIXEL_RGB
    PYNQ_AVAILABLE = True
except ImportError:
    PYNQ_AVAILABLE = False

logger = logging.getLogger(__name__)

# Fixed-point parameters — must match cosine_match.h
EMB_DIM      = 128
MAX_USERS    = 32
Q_FRAC_BITS  = 14          # Q2.14 format
Q_SCALE      = 2 ** Q_FRAC_BITS   # 16384

# AXI GPIO register
_GPIO_DATA   = 0x000

# cosine_match_accel AXI-Lite offsets
_CM_CTRL     = 0x00
_CM_DB_LO    = 0x10
_CM_DB_HI    = 0x14
_CM_NUSERS   = 0x18
_CM_BEST_IDX = 0x20
_CM_BEST_SCR = 0x28
_CM_QUERY    = 0x100        # 64 × uint32 (128 × int16)

_CM_START    = 0x1
_CM_DONE     = 0x2
_CM_IDLE     = 0x4


class FPGAInterface:
    """
    PS↔PL interface for the face recognition kill switch.

    After init:
      - HDMI IN/OUT pipeline is running continuously in hardware.
      - cosine_match_accel BRAM is pre-loaded with enrolled embeddings.
      - The PS only needs to call set_authorization_status() and
        run_cosine_match() each frame.
    """

    def __init__(self, overlay, verbose: bool = False):
        self.overlay  = overlay
        self.verbose  = verbose
        self._authorized = False

        # Contiguous PYNQ buffer for enrolled embeddings (DMA accessible)
        self._db_buf     = None
        self._db_nusers  = 0

        self._init_gpio()
        self._init_cosine_match()
        self._init_video()

        self.set_authorization_status(False)
        logger.info("FPGA interface ready")

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    def _init_gpio(self):
        if not PYNQ_AVAILABLE:
            self._gpio = None
            return
        try:
            self._gpio = self.overlay.axi_gpio_0
        except AttributeError:
            logger.error("axi_gpio_0 not found in overlay")
            raise

    def _init_cosine_match(self):
        """Bind to the HLS cosine match accelerator."""
        if not PYNQ_AVAILABLE:
            self._cm = None
            return
        try:
            # PYNQ auto-names HLS IPs from the .hwh hardware description
            self._cm = self.overlay.cosine_match_accel_0
            # Allocate a physically contiguous buffer for enrolled embeddings.
            # The HLS core reads this via its AXI4 master (DMA).
            # Shape: (MAX_USERS × EMB_DIM) × int16
            self._db_buf = allocate(
                shape=(MAX_USERS * EMB_DIM,), dtype=np.int16
            )
            self._db_buf[:] = 0
            logger.info("cosine_match_accel bound, DB buffer allocated")
        except AttributeError:
            logger.warning(
                "cosine_match_accel_0 not found in overlay — "
                "falling back to CPU cosine similarity"
            )
            self._cm = None

    def _init_video(self):
        if not PYNQ_AVAILABLE:
            self._hdmi_in = self._hdmi_out = None
            return
        try:
            self._hdmi_in = self.overlay.video.hdmi_in
            self._hdmi_in.configure(PIXEL_RGB)
            self._hdmi_in.start()

            self._hdmi_out = self.overlay.video.hdmi_out
            self._hdmi_out.configure(self._hdmi_in.mode, PIXEL_RGB)
            self._hdmi_out.start()

            logger.info(
                f"HDMI {self._hdmi_in.mode.width}×{self._hdmi_in.mode.height}"
                f"@{self._hdmi_in.mode.fps}fps"
            )
        except AttributeError as e:
            logger.error(f"HDMI init failed: {e}")
            raise

    # ------------------------------------------------------------------
    # Enrolled user database — keep FPGA BRAM in sync
    # ------------------------------------------------------------------

    def update_database(self, embeddings_dict: dict):
        """
        Load enrolled user embeddings into the FPGA cosine-match accelerator.

        Must be called once at startup and after every enrollment.

        Args:
            embeddings_dict: {username: np.ndarray (128-D float32)} from UserDatabase.
                             Only the first MAX_USERS entries are loaded.
        """
        if not PYNQ_AVAILABLE or self._cm is None or self._db_buf is None:
            return

        users = list(embeddings_dict.items())[:MAX_USERS]
        self._db_nusers  = len(users)
        self._user_index = [u for u, _ in users]   # index → username mapping

        # Convert float32 → int16 Q2.14 and write to DMA buffer
        for i, (_, emb) in enumerate(users):
            q = np.clip(
                np.round(emb.astype(np.float64) * Q_SCALE),
                -32768, 32767
            ).astype(np.int16)
            self._db_buf[i * EMB_DIM : (i + 1) * EMB_DIM] = q

        # Write db buffer physical address and user count to HLS registers
        self._cm.write(_CM_DB_LO, int(self._db_buf.physical_address & 0xFFFFFFFF))
        self._cm.write(_CM_DB_HI, 0)
        self._cm.write(_CM_NUSERS, self._db_nusers)

        if self.verbose:
            logger.debug(f"DB updated: {self._db_nusers} user(s) loaded to FPGA")

    # ------------------------------------------------------------------
    # Cosine match accelerator
    # ------------------------------------------------------------------

    def run_cosine_match(
        self, embedding: np.ndarray, timeout: float = 0.01
    ) -> Tuple[Optional[str], float]:
        """
        Run cosine similarity search on FPGA.

        Sends the query embedding to the HLS IP via AXI-Lite, starts the
        accelerator, waits for completion, and reads back the best match.

        Args:
            embedding: 128-D float32 unit-norm query embedding.
            timeout:   Seconds to wait for accelerator completion.

        Returns:
            (username, similarity_score) or (None, 0.0) if no users enrolled
            or FPGA unavailable.
        """
        if (not PYNQ_AVAILABLE or self._cm is None
                or self._db_nusers == 0):
            return None, 0.0

        # --- Encode query as Q2.14 int16, pack two per 32-bit word ---
        q_int = np.clip(
            np.round(embedding.astype(np.float64) * Q_SCALE),
            -32768, 32767
        ).astype(np.int16)

        # Write 128 int16 values as 64 uint32 words to AXI-Lite offset 0x100
        q_words = q_int.view(np.uint32)          # reinterpret: pair of int16 → uint32
        for i, word in enumerate(q_words):
            self._cm.write(_CM_QUERY + i * 4, int(word))

        # --- Start the accelerator ---
        self._cm.write(_CM_CTRL, _CM_START)

        # --- Poll ap_done ---
        t0 = time.time()
        while True:
            status = self._cm.read(_CM_CTRL)
            if status & _CM_DONE:
                break
            if time.time() - t0 > timeout:
                logger.warning("cosine_match_accel timeout")
                return None, 0.0

        # --- Read results ---
        best_idx   = self._cm.read(_CM_BEST_IDX)
        raw_score  = self._cm.read(_CM_BEST_SCR)

        # best_score is Q4.28 fixed-point — convert to float
        # Treat raw uint32 as signed int32, then scale
        signed_score = np.int32(raw_score)
        best_score   = float(signed_score) / (2 ** 28)

        if best_idx < len(self._user_index):
            username = self._user_index[best_idx]
        else:
            username = None

        if self.verbose:
            logger.debug(
                f"cosine_match: best={username} score={best_score:.4f} "
                f"({self._db_nusers} users, idx={best_idx})"
            )

        return username, best_score

    # ------------------------------------------------------------------
    # Kill-switch control (1-bit AXI GPIO)
    # ------------------------------------------------------------------

    def set_authorization_status(self, is_authorized: bool):
        """
        Set HDMI kill-switch state via AXI GPIO.

        Args:
            is_authorized: True  → HDMI IN passthrough (PC signal visible)
                           False → camera feed on display (PC signal blocked)
        """
        self._authorized = is_authorized

        if not PYNQ_AVAILABLE or self._gpio is None:
            logger.info(f"[Mock] Kill-switch → {'AUTH' if is_authorized else 'UNAUTH'}")
            return
        try:
            self._gpio.write(_GPIO_DATA, int(is_authorized))
        except Exception as e:
            logger.error(f"GPIO write failed: {e}")

    # ------------------------------------------------------------------
    # Camera frame injection (VDMA path — displayed when unauthorized)
    # ------------------------------------------------------------------

    def write_camera_frame(self, frame: np.ndarray):
        """Push annotated camera frame to VDMA output buffer (BGR input)."""
        if not PYNQ_AVAILABLE or self._hdmi_out is None:
            return
        try:
            out_frame = self._hdmi_out.newframe()
            out_frame[:] = frame[:, :, ::-1]   # BGR → RGB
            self._hdmi_out.writeframe(out_frame)
        except Exception as e:
            logger.error(f"VDMA frame write failed: {e}")

    # ------------------------------------------------------------------
    # Cleanup
    # ------------------------------------------------------------------

    def shutdown(self):
        try:
            self.set_authorization_status(False)
            if PYNQ_AVAILABLE:
                if self._hdmi_in:
                    self._hdmi_in.stop()
                if self._hdmi_out:
                    self._hdmi_out.stop()
                if self._db_buf is not None:
                    self._db_buf.freebuffer()
            logger.info("FPGA interface shutdown")
        except Exception as e:
            logger.error(f"Shutdown error: {e}")